Destructive changeset with an antlernative package.xml
micheletriaca/sfdy pull request #14
Opened 2021-03-09 12:57 UTC by zerbfra

Hi Michele,
this is a PR to make sfdy work with destructive changesets and a custom package.xml

As an example, you can use it with this command:

```
sfdy deploy -u <user> -p <password> -s --package ./destructive-changeset/destructiveChanges.xml --destructive
```

As you can see, I'm using both the package and the destructive options.
With the first one you specify where your custom package is stored (it could also be a custom package to use in other parts of sfdy). With the second one you declare a destructive.

THIS IS A DRAFT - WIP

2021-03-09 13:11 UTC, zerbfra commented on src/deploy/index.js
> -  if (!specificFilesMode && destructive) {
here there is something that it was unexpected: ! specificFilesMode should be specificFilesMode?

2021-03-09 13:11 UTC, zerbfra commented
If we agree on a solution for the available options I will also update the docs - let me know

2021-03-09 13:44 UTC, zerbfra commented
Merged with only one option "destructive [file]"

Allowed options: 

```
sfdy deploy -u <user> -p <password> -s --destructive ./destructive-changeset/destructiveChanges.xml
```

or

```
sfdy deploy -u <user> -p <password> -s --files="..."  --destructive
```

or

```
sfdy deploy -u <user> -p <password> -s --diff="..."  --destructive
```

I have also changed the condition at line 85.

2021-03-10 12:04 UTC, micheletriaca commented
Great job

2021-03-11 18:11 UTC, micheletriaca requested changes

2021-03-13 08:46 UTC, zerbfra commented on src/utils/package-utils.js
> +      return (await parseXml(fs.readFileSync(`${pathService.getBasePath()}/${opts.specificPackage}`))).Package
fixed with your code

2021-03-14 08:37 UTC, micheletriaca approved these changes

2021-03-14 08:37 UTC, merged

2021-03-26 07:41 UTC, micheletriaca commented
close #9